# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('risk_field_name', models.TextField()),
                ('risk_field_data_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskFieldValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('risk_field_value', models.TextField()),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskField')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskType'),
        ),
    ]
