# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfield',
            name='risk_type_id',
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='riskfields', to='risks.RiskType'),
            preserve_default=False,
        ),
    ]
