# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20180211_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risk_field_data_type',
            field=models.CharField(choices=[('Text', 'TEXT'), ('Number', 'NUMBER'), ('Date', 'DATE'), ('Enum', 'ENUM')], max_length=10),
        ),
    ]
