# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_auto_20180211_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
